name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-windows.yml@269d875599c92395f7fa99cab43edc1820798e61
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
        salt_state:
          - netbanner
        salt_pillar_root:
          - ./tests/pillar/test-windows-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
